name: moya_pbl2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  intl: ^0.20.2
  image_picker: ^1.0.7
  file_picker: ^8.0.0
  dart_jsonwebtoken: ^2.8.0
  firebase_storage: ^12.4.10
  cloudflare_r2: ^0.0.14
  http: ^1.6.0
  http_parser: ^4.1.2
  fl_chart: ^1.2.0
  pdf: ^3.11.0
  printing: ^5.11.1
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  screenshot: ^3.0.0
  url_launcher: ^6.3.2
  open_filex: ^4.7.0
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.0.0
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconApp.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon1.png
    - assets/images/icon2.png
    - assets/images/cloud1.png
    - assets/images/cloud2.png
    - assets/images/icons.png
    - assets/images/icons1.png
    - assets/images/emot1.png
    - assets/images/emot2.png
    - assets/images/emot3.png
    - assets/images/emot4.png
    - assets/images/emot5.png
    - assets/images/Happy.png
    - assets/images/Tired.png
    - assets/images/Angry.png
    - assets/images/Stressed.png
    - assets/images/Relaxed.png
    - assets/images/Desperate.png
    - assets/images/Sad.png
    - assets/images/Grateful.png
    - assets/images/back.png
    - assets/images/calendar.png
    - assets/images/note.png
    - assets/images/arrow_right.png
    - assets/images/icon_journal.png
    - assets/images/icon_consult.png
    - assets/images/icon_chat.png
    - assets/images/icon_report.png
    - assets/images/icon_Home.png
    - assets/images/icon_Community.png
    - assets/images/icon_plus.png
    - assets/images/icon_Analytics.png
    - assets/images/icon_Profile.png
    - assets/images/profile.png
    - assets/images/icon_avg.png
    - assets/images/icon_streak.png
    - assets/images/icon_mon.png
    - assets/images/icon_thu.png
    - assets/images/icon_wed.png
    - assets/images/icon_tue.png
    - assets/images/icon_fri.png
    - assets/images/icon_sat.png
    - assets/images/icon_sun.png
    - assets/images/icon_noday.png
    - assets/images/emot0.png
    - assets/images/bg_chat.png