// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbO3z0P1cHqcFcqnCQHmxoWPveUdPAI8',
    appId: '1:698348593842:web:48e1f4075f714e86205fab',
    messagingSenderId: '698348593842',
    projectId: 'moyaapp-pbl2',
    authDomain: 'moyaapp-pbl2.firebaseapp.com',
    storageBucket: 'moyaapp-pbl2.firebasestorage.app',
    measurementId: 'G-KVS6C8W4YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChw-AN9qVWpW3Nf2oZvctNQ9GQ9U2PE-E',
    appId: '1:698348593842:android:c14a867443162b25205fab',
    messagingSenderId: '698348593842',
    projectId: 'moyaapp-pbl2',
    storageBucket: 'moyaapp-pbl2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHrxnyxYOlv2dJmfojDFzNI8XsfghA9Pg',
    appId: '1:698348593842:ios:5487efcd97504efc205fab',
    messagingSenderId: '698348593842',
    projectId: 'moyaapp-pbl2',
    storageBucket: 'moyaapp-pbl2.firebasestorage.app',
    iosBundleId: 'com.example.moyaPbl2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHrxnyxYOlv2dJmfojDFzNI8XsfghA9Pg',
    appId: '1:698348593842:ios:5487efcd97504efc205fab',
    messagingSenderId: '698348593842',
    projectId: 'moyaapp-pbl2',
    storageBucket: 'moyaapp-pbl2.firebasestorage.app',
    iosBundleId: 'com.example.moyaPbl2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmbO3z0P1cHqcFcqnCQHmxoWPveUdPAI8',
    appId: '1:698348593842:web:f824d9a816086b90205fab',
    messagingSenderId: '698348593842',
    projectId: 'moyaapp-pbl2',
    authDomain: 'moyaapp-pbl2.firebaseapp.com',
    storageBucket: 'moyaapp-pbl2.firebasestorage.app',
    measurementId: 'G-RYN3D9FC7M',
  );
}
